version: '3'
services: 
  myfirstapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: node_modules/.bin/nodemon  --exec npm start
    environment: 
      NODE_ENV: development
    ports:
      - 80:3000
    volumes:
      - .:/home/app/MyFirstAPIRest
      - /home/app/MyFirstAPIRest/node_modules
    network_mode: bridge
    